version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 200
    funlen:
      lines: 150
      statements: 120
    gocognit:
      min-complexity: 32
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
